config/routes.rb
Ratebeer::Application.routes.draw do

  resources :styles

  resources :memberships

  resources :beer_clubs

  root 'breweries#index'

  resources :users
  resources :beers
  resources :breweries
  resources :ratings
  resources :sessions, only: [:new, :create, :destroy]
  resources :ratings, :only => [:index, :new, :create, :destroy]
  resources :places, only:[:index, :show]

  get 'kaikki_bisset', to: 'beers#index'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  get 'places', to: 'places#index'

  post 'places', to: 'places#search'

  delete 'signout', to: 'sessions#destroy'
  delete 'sessions', to: 'sessions#destroy'

end

app/models/beer.rb
class Beer < ActiveRecord::Base
  include RatingAverage

  validates :name, length: {minimum: 1}
  validates :style, length: {minimum: 1}

  has_many :ratings, :dependent => :destroy
  has_many :raters, through: :ratings, source: :user

  belongs_to :brewery
  belongs_to :style

  #def average_rating
    #ra_sum = 0.0
    #ratings.each do |rat|
    #  ra_sum += rat.score
    #end
    #ra_sum / ratings.count

   # ratings.sum('score').to_f / ratings.count
  #end

  def to_s
    "#{name} #{brewery.name}"
  end

end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :set_beer, only: [:show, :edit, :update, :destroy]
  before_action :set_breweries_and_styles_for_template, only: [:new, :edit, :create]
  before_action :ensure_that_signed_in, except: [:index, :show]

  # GET /beers
  # GET /beers.json
  def index
    @beers = Beer.all

    order = params[:order] || 'name'

    case order
      when 'name' then @beers.sort_by!{ |b| b.name }
      when 'brewery' then @beers.sort_by!{ |b| b.brewery.name }
      when 'style' then @beers.sort_by!{ |b| b.style.name }
    end
  end

  # GET /beers/1
  # GET /beers/1.json
  def show
    @rating = Rating.new
    @rating.beer = @beer
  end

  # GET /beers/new
  def new
    @beer = Beer.new
  end

  # GET /beers/1/edit
  def edit
  end

  # POST /beers
  # POST /beers.json
  def create
    @beer = Beer.new(beer_params)

    respond_to do |format|
      if @beer.save
        format.html { redirect_to @beer, notice: 'Beer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @beer }
      else
        format.html { render action: 'new' }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beers/1
  # PATCH/PUT /beers/1.json
  def update
    respond_to do |format|
      if @beer.update(beer_params)
        format.html { redirect_to @beer, notice: 'Beer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beers/1
  # DELETE /beers/1.json
  def destroy
    @beer.destroy
    respond_to do |format|
      format.html { redirect_to beers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer
      @beer = Beer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_params
      params.require(:beer).permit(:name, :style, :brewery_id)
    end

  def set_breweries_and_styles_for_template
    @breweries = Brewery.all
    @styles = ["Weizen", "Lager", "Pale ale", "IPA", "Porter"]
  end
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/_form.html.erb
<%= form_for(@beer) do |f| %>
  <% if @beer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer.errors.count, "error") %> prohibited this beer from being saved:</h2>

      <ul>
      <% @beer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :style %><br>
    <%= f.select(:style, options_for_select(@styles, :style))  %>
  </div>
  <div class="field">
    <%= f.label :brewery_id %><br>
    <%= f.select(:brewery_id, options_from_collection_for_select(@breweries,:id,:name)) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beers/edit.html.erb
<h1>Editing beer</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer %> |
<%= link_to 'Back', beers_path %>

app/views/beers/index.html.erb
<h1>Listing beers</h1>

<table>
  <thead>
  <tr>
    <th> <%= link_to 'Name', beers_path(order:"name") %> </th>
    <th> <%= link_to 'Style', beers_path(order:"style") %> </th>
    <th> <%= link_to 'Brewery', beers_path(order:"brewery") %> </th>
  </tr>
  </thead>

  <tbody>
  <% @beers.each do |beer| %>
      <tr>
        <td><%= link_to beer.name, beer %></td>
        <td><%= link_to beer.style, beer.style %></td>
        <td><%= link_to beer.brewery.name, beer.brewery %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Beer', new_beer_path %>
<%= link_to 'list of breweries', breweries_path %>

app/views/beers/new.html.erb
<h1>New beer</h1>

<%= render 'form' %>

<%= link_to 'Back', beers_path %>

app/views/beers/show.html.erb
<p id="notice"><%= notice %></p>

<h2> <%= @beer %> </h2>

<p>
  <strong>Style:</strong>
  <%= @beer.style %>
</p>

<% if @beer.ratings.empty? %>
    <p>beer has not yet been rated!</p>
<% else %>
    <p>has been rated <%= @beer.ratings.count %> times, average score <%= @beer.average_rating %></p>
<% end %>

<% if current_user %>

    <h4>give a rating:</h4>

    <%= form_for(@rating) do |f| %>
        <%= f.hidden_field :beer_id %>
        score: <%= f.number_field :score %>
        <%= f.submit %>
    <% end %>

    <%= link_to 'Edit', edit_beer_path(@beer) %>

<% end %>